CREATE DATABASE ${POSTGRES_DB};
CREATE USER ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';
ALTER ROLE ${POSTGRES_USER} SET client_encoding TO 'utf8';
ALTER ROLE ${POSTGRES_USER} SET default_transaction_isolation TO 'read committed';
ALTER ROLE ${POSTGRES_USER} SET timezone TO 'Europe/Moscow';
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};