# Generated by Django 4.2 on 2023-04-29 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSource',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('chart_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastSource',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('chart_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPrameter',
            fields=[
                ('param_key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('tooltip', models.CharField(max_length=30)),
                ('meas_unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('timezone', models.CharField(default='UTC', max_length=40)),
            ],
            options={
                'unique_together': {('name', 'region', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ForecastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_relative_url', models.CharField(max_length=100)),
                ('forecast_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.forecastsource')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.location')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_datetime', models.DateTimeField(default=datetime.datetime(2023, 4, 29, 22, 6, 10, 821955))),
                ('start_forecast_datetime', models.DateTimeField()),
                ('data_json', models.JSONField()),
                ('forecast_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.forecastsource')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.location')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_relative_url', models.CharField(max_length=100)),
                ('archive_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.archivesource')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.location')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_datetime', models.DateTimeField(default=datetime.datetime(2023, 4, 29, 22, 6, 10, 822612))),
                ('data_json', models.JSONField()),
                ('archive_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.archivesource')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascraper.location')),
            ],
        ),
    ]
