# Generated by Django 4.2 on 2023-06-20 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['archive_template', 'record_datetime']},
        ),
        migrations.AddField(
            model_name='archive',
            name='record_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='archive',
            name='scraped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 19, 16, 4, 673979)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='scraped_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterIndexTogether(
            name='archive',
            index_together={('archive_template', 'record_datetime')},
        ),
    ]
