# Generated by Django 4.2 on 2023-04-29 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivetemplate',
            options={'ordering': ['archive_source', 'location']},
        ),
        migrations.AlterModelOptions(
            name='forecasttemplate',
            options={'ordering': ['forecast_source', 'location']},
        ),
        migrations.AlterField(
            model_name='archive',
            name='scraped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 22, 19, 26, 379009)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='scraped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 22, 19, 26, 378423)),
        ),
    ]
