# Generated by Django 4.2 on 2023-04-29 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0002_alter_archivetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivetemplate',
            options={'ordering': ['location', 'archive_source']},
        ),
        migrations.AlterModelOptions(
            name='forecasttemplate',
            options={'ordering': ['location', 'forecast_source']},
        ),
        migrations.AlterField(
            model_name='archive',
            name='scraped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 22, 20, 45, 987353)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='scraped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 22, 20, 45, 986772)),
        ),
    ]
